---
- name: install
  yum: name=ntp state=present
  tags: ntp
  
- name: configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify:restart ntp
   
- name: start the ntp service
  command: name=ntpd state=started enabled=yes
  tags: ntp
   
- name: test to see if selinux is enabled
  command: getforce
  register: sestatus
  changed_when: false   
   
   